//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Enyities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public int UserId { get; set; }
        public int ArticleID { get; set; }
        public string CommentText { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual BlogUser BlogUser { get; set; }
    }
}
